### ISSUE TITLE
Stuck on loading.....

### ISSUE THREAD

**Issue by ghost** [getbible/Joomla-3-Component#11]
I have installed getbible on joomla. It previously worked on another installation with the same version. Now when I install getbible on this joomla site that I have now it is stuck on loading....

That is the bible never show. The menu shows wheel search chapter A. But the bible doesnt load. 

What is the error?

I have created both a Json menu item on one menu and then also a App menu item on the main menu. It still doesnt work.  I cannot see the bible text.

**Comment by ghost** [comment]
I was able to get it working by changing the template from light blog template to protostar template. 

I would like still to get getbible working for light blog template maybe you can try to sort it out and make an update so that getbible works for light blog template too.


http://joothemes.net/responsive-joomla-templates/light-blog-free-joomla-3-rwd-template

**Comment by ghost** [comment]
I close this issue because I found a widescreen theme that works with getbible. It is JSN Boot Pro.

So no need to make an getbible update for this issue.

**Comment by Llewellynvdm** [comment]
Sorry about that... getBible uses uikit version 2, so to get the most out of it there are two options.

One use a Yootheme template, or insure that in the getBible global options you force the UIkit to load. Hope this may help in the future :)
