### ISSUE TITLE
Get the name of the book

### ISSUE THREAD

**Issue by oemel09** [getbible/Joomla-3-Component#12]
Hey, I just wondered if you could also give out the name of the book in the requested language?
Thanks so much for providing this API!

**Comment by Llewellynvdm** [comment]
Yes sure, sorry for the slow reply... anyway take a look at this url:
https://getbible.net/index.php?option=com_getbible&task=bible.books&format=json&v=kjv

Just change the version to that of your choice.

**Comment by oemel09** [comment]
Hey, thanks for the reply! That's kinda what I looked for. But I tried it out with say e.g. the German version. 
So the for the URL instead of v=kjv I put v=elberfelder
So I expected to get a list of all the German names of the books. 
But I got the very same result... Did I miss out something?

**Comment by Llewellynvdm** [comment]
Sure, on getBible all book names are still in English, but the component does allow you to setup your own API and load your own book names on your own Joomla website. Please review [these four videos](https://getbible.net/main-component) for the guidelines of how to achieve this.

**Comment by oemel09** [comment]
Oh, thanks for that, I think I got it. I didn't mention yet that I'm not using the whole application you're poviding. I just use the API directly because it's just a small project which I'm working on. So did I get that right that without the extra component there is not way to get the correct translation of the books name yet?

**Comment by Llewellynvdm** [comment]
Sure if you give us the Translation names in the spreadsheet. I explained in the one video about adding your own names that you can send me the spreadsheet then we will add it to the getBible.net API

Did you watch the videos?

**Comment by Llewellynvdm** [comment]
Thank you for the spreadsheet, I should have it ready some time next week...

**Comment by oemel09** [comment]
Thank you too!
No hurry, take your time :)
