### ISSUE TITLE
JS Conflicts

### ISSUE THREAD

**Issue by Mesack** [getbible/Joomla-3-Component#13]
Hi, 
Thanks for writing creating the GetBible API. I'm really hoping to use it in a  couple of projects. I have a problem which i'm stuck with at the present time. I'm currently trying to use the API from a local install and have the Bibles installed locally but the chapters are not loading and just seem to hang. Using Chrome dev tools I can see that the offline.min js is not loading and I think its a JS conflict somewhere causing the issue. I've tried loading the page using basic template but I still get the same issue any suggestions? Thanks.

**Comment by Llewellynvdm** [comment]
Hi, not sure what that could be.. what do you see in the console of firebug? is the offline.min.js file in the local media folder for getBible?

IF I could see more I could maybe help... hard to really know :)

**Comment by Llewellynvdm** [comment]
Sorry for the slow reply.. been under heavy load of work. It should work... it works on many sites of my own and countless other... so it could me that you just need to reinstall... what have you tried so far?

**Comment by Mesack** [comment]
Thanks, I totally understand, I know getBible works. I think the problem will be to do with the template I'm using and I just don't have the time to try and fix it so I've decided to use the API with a fresh install using Yoo Theme template with UIkit 2 as recommended by yourself.
