### ISSUE TITLE
Invalid JSON?

### ISSUE THREAD

**Issue by vicmortelmans** [getbible/Joomla-3-Component#14]
The API's output JSON is between round brackets and therefore evaluated as invalid e.g. by YQL:

https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20json%20where%20url%3D%22https%3A%2F%2Fgetbible.net%2Fjson%3Fpassage%3D1Jn3%3A16%22&diagnostics=true

Are the brackets needed for some reason?

Best regards,
Vic

**Comment by Llewellynvdm** [comment]
That is for jQuery, you can add `&raw=true` to get raw json.

Like this https://getbible.net/json?p=Psalms&raw=true

**Comment by vicmortelmans** [comment]
Thanks, that solved it!
