### ISSUE TITLE
cUrl

### ISSUE THREAD

**Issue by oemel09** [getbible/Joomla-3-Component#15]
Hey, I tried to get the contents from your web api in php via cUrl... But it said Error 403 access forbidden. Malware detected.

**Comment by Llewellynvdm** [comment]
Please checkout the [script used in this Plugin](https://github.com/getbible/Joomla-3-Load-Scripture-Plugin/blob/master/loadscripture.php#L943) for best practice in using curl.

Let me know if you are still having trouble.

**Comment by oemel09** [comment]
Thank you so much! It worked out :)
First it didn't work, then I commented out these two lines because I'm not quite sure how to set those variables... I'm not that much into php yet...
//	curl_setopt($curl, CURLOPT_HTTPHEADER, $this->cURLheader);
//	curl_setopt($curl, CURLOPT_REFERER, $this->referer);
But without these two lines it worked fine! :) Thanks again!

**Comment by Llewellynvdm** [comment]
The first var is set here [$this->cURLheader](https://github.com/getbible/Joomla-3-Load-Scripture-Plugin/blob/master/loadscripture.php#L438) the second var is set here [$this->referer ](https://github.com/getbible/Joomla-3-Load-Scripture-Plugin/blob/master/loadscripture.php#L437)

Do remember the $this->var refers to a class variable, and if you not in a class you can drop the this and just use $cURLheader or $referer

Great that you got it to work :+1:
