### ISSUE TITLE
Remove the () around the json in the API answer

### ISSUE THREAD

**Issue by DanielPopOut** [getbible/Joomla-3-Component#17]
Hey, is it possible to remove the () around the json answer of the bible api ? 
({JsonAnswer}) --> {JsonAnswer}

**Comment by Llewellynvdm** [comment]
You can add &raw=true to get raw json.
Like this https://getbible.net/json?p=Psalms&raw=true

**Comment by DanielPopOut** [comment]
I searched and did not find ! Thks a lot !

**Comment by Llewellynvdm** [comment]
Okay... [here is the issue](https://github.com/getbible/Joomla-3-Component/issues/14) that deal with the same :)

**Comment by Llewellynvdm** [comment]
And [this one](https://github.com/getbible/Bibles/issues/7)...

**Comment by Llewellynvdm** [comment]
But hey you are welcome, let me know if there is anything I can do to help!
