### ISSUE TITLE
Entire bible returned with invalid passage

### ISSUE THREAD

**Issue by sunnychen43** [getbible/Joomla-3-Component#18]
When I make a request with an invalid passage field like:
http://getbible.net/json?passage=aaaaa&version=kjv
it will return the entire bible.

Out of the english versions, this only happens when version=kjv.

**Comment by sunnychen43** [comment]
Sorry I missed it, this happens anytime version is set to a valid version, but passage is invalid.

However, 
http://getbible.net/json?passage=aaaaa
returns NULL as expected.

**Comment by Llewellynvdm** [comment]
Amazing news, have a look at https://github.com/getbible/v1#getbible-api-v1 the new easy expansion of the getBible API
