### ISSUE TITLE
Select Version Function Not Working

### ISSUE THREAD

**Issue by laurenjmiller** [getbible/Joomla-3-Component#19]
Recently, the Select Version option has been non-functional. The drop down list shows no information to select.

**Comment by Llewellynvdm** [comment]
You can do two things here. One clear your browser **memory completely** also the **cache** and if it still does not work, please take a screen shot and post it here so I can see exactly where the issue is happening.

But I think the browser memory clear usually fix these things.

**Comment by Llewellynvdm** [comment]
oops wrong forum.... lol clearing the browser will not work, sorry I thought this was a [JCB](https://github.com/vdm-io/Joomla-Component-Builder) issue.

Please send me a screen shot :+1:

**Comment by laurenjmiller** [comment]
You can see the screenshot here:
![](https://kingdomwebsupport.com/images/GB_1.jpg)

**Comment by Llewellynvdm** [comment]
Okay that is weird... let me check the main site, one moment.

Okay it still works on http://getbible.net/

What version of Joomla are you on and what PHP version.

**Comment by Llewellynvdm** [comment]
I think I found the issue, my ssl is down of getBible.net let me quickly fix that and then we try again.

**Comment by Llewellynvdm** [comment]
Okay ssl is not renewed please try again.

**Comment by laurenjmiller** [comment]
That was it! All fixed now. Thank you for your prompt response. -Lauren
