### ISSUE TITLE
Add option to install Bibles from a local folder.

### ISSUE THREAD

**Issue by Llewellynvdm** [getbible/Joomla-3-Component#2]
The component installs the Bibles directly from getBible at this time, the option to also install the Bibles from a local folder, located on the same server as the Joomla website seems like a handy feature to add.

**Comment by ef-five** [comment]
When I place the bible in the local folder and then go to administration Install Bibles I get an Error and it says  "Please try again later! Please contact me at info@getbible.net if you have any further questions.".

**Comment by Llewellynvdm** [comment]
Hi, we recommend you using the getBible default way of installing the scripture/Bibles. Yet how to install from a local folder would need some change to the global component settings as well as a few other things. Please take a look at this short video tutorial  http://youtu.be/Um-JnY02IY4

If this does not solve your problem, please make sure you are on the latest version and that your server configurations are correct. If all these things are set correctly and it still does not work, please let me know.
