### ISSUE TITLE
Estonian version is missing many parts and broken

### ISSUE THREAD

**Issue by ghost** [getbible/Joomla-3-Component#20]
books nr 2-39 are missing completely and others have missing verses or verses with one letter

I am willing to make a fixed version from say [this](http://dev.piibel.net/ebook/)

**Comment by Llewellynvdm** [comment]
Okay please look at [this file,](https://github.com/getbible/Bibles/blob/master/Estonian__Estonian__estonian__LTR.txt) and update that file (same format). Then make a pull request and we will review.

**Comment by ibex-of-entropy** [comment]
[Estonian__Estonian_1997__estonian__LTR.txt](https://github.com/getbible/Joomla-3-Component/files/1591184/Estonian__Estonian_1997__estonian__LTR.txt)
