### ISSUE TITLE
Using request.js returns "Malware detected"

### ISSUE THREAD

**Issue by sukkergris** [getbible/Joomla-3-Component#23]
Trying to use nodejs to access the api. But I just get the above result.
<h4>403: Access Forbidden</h4> Malware detected.
(http://getbible.net/json?scrip=Acts%203:17-4;2:1)
Any thoughts? :)

**Comment by Llewellynvdm** [comment]
This may be due to the `jsonp` return set that is used for jQuery, add `&raw=true` to your query and see if the issue gets resolved.

**Comment by sukkergris** [comment]
Thanks for the reply. I just tried - but same result. The request is issued from node.js maby the issue is here.  (http://getbible.net/json?scrip=Acts%203:17-4;2:1&raw=true)

**Comment by Llewellynvdm** [comment]
Amazing news, have a look at https://github.com/getbible/v1#getbible-api-v1 the new easy expansion of the getBible API
