### ISSUE TITLE
Missing quotes for returning Son

### ISSUE THREAD

**Issue by sholekov** [getbible/Joomla-3-Component#24]
at that Uri https://getbible.net/json?getbible=jQuery2240006153137834923106_1531040227276&p=Psalms%20119&v=bulgarian1940&_=1531040227279 the console return "Uncaught SyntaxError: Invalid or unexpected token"
and after last char hasn't closing quotes {"verse_nr":171,"verse":"\u0423\u0441\u0442\u043d\u0438\u0442\u0435 \u043c\u0438 \u0449\u0435 \u0438\u0437\u043b\u0438\u0432\u0430\u0442 \u0445\u0432\u0430\u043b\u0435\u043d\u0438\u0435, \u0417\u0430\u0449\u043e\u0442\u043e \u043c\u0435 \u0443\u0447\u0438\u0448 \u043d\u0430 \u043f\u043e\u0432\u0435\u043b\u0435\u043d\u0438\u044f\u0442\u0430 \u0421\u0438.\n"},"172":{"verse_nr":172,"verse":"\u0415\u0437\u0438\u043a\u044a\u0442 \u043c\u0438 \u0449\u0435 \});

**Comment by Llewellynvdm** [comment]
Amazing news, have a look at https://github.com/getbible/v1#getbible-api-v1 the new easy expansion of the getBible API
