### ISSUE TITLE
Adding book names for new language

### ISSUE THREAD

**Issue by mike-sfg** [getbible/Joomla-3-Component#26]
I would like to add Bible book names for the Simplified Chinese Bible versions. In your help video, you mention that we can email you a spreadsheet with the book name information so that it can be added to the database and new versions of GetBible.

How can I contact you and send the list?  Thanks!

Michael

**Comment by Llewellynvdm** [comment]
I am working on a whole new approach to this in a whole new getBible component. So if you can hold on just a little more, and we will roll out the new version, which will be fully integrate with git/repo based expansion for the community that will make it a whole lot easier to expand for all.

**Comment by mike-sfg** [comment]
Okay, thank you.
