### ISSUE TITLE
Content-Type: text/html

### ISSUE THREAD

**Issue by mike-sfg** [getbible/Joomla-3-Component#27]
When I make a request to the API, the response headers include:

Content-Type: text/html; charset=UTF-8
I believe that when requesting 'jsonp' (json with padding), the content-type should be set to: 'application/javascript'

On my server running a getBible API, my cross domain requests were being blocked. But I saw that it worked when I disabled this Apache setting:

Header always set X-Content-Type-Options nosniff

This setting (if I understand correctly) prevents browsers from auto-detecting and overriding the MimeTypes sent in the headers. It appears the API is sending it as 'type/html' and my browser recognizes is as a javascript function, but can't override the type.

Thanks for your help.

**Comment by Llewellynvdm** [comment]
We are working on this in a whole new release of getBible API application. Noting we can do for now to this version. But we are aware of this issue.

**Comment by mike-sfg** [comment]
Okay, thank you.

**Comment by mike-sfg** [comment]
I ended up using a php file on my Wordpress site to act as a proxy for fetching the json from my subdomain running Joomla with GetBible. Here is a screenshot of a popup working:
![image](https://user-images.githubusercontent.com/41925797/44599677-b6e50800-a79c-11e8-877a-47b4dea35dde.png)

**Comment by Llewellynvdm** [comment]
Wonderful :+1:
