### ISSUE TITLE
Can't verifiy SSL certificate error 

### ISSUE THREAD

**Issue by Node815** [getbible/Joomla-3-Component#28]
SplFileObject::__construct(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed 

Joomla 3.9.0 

This is when installing Bibles through the interface.

**Comment by Llewellynvdm** [comment]
hmm strange I have not seen that before.

I am working on an upgrade I hope to release in the new year. getBible is one of my oldest projects, and I am planning to release a fully redesigned version, that will be fully mapped in [JCB](https://github.com/vdm-io/Joomla-Component-Builder). This way it will be easy to extend the component on your own (beyond the basic foundation), and further the development of getBible inside of JCB.

So all I can say for now, is please hold on... I will get the new version out in the next few months. This will resolve all kind of issues.

**Comment by Llewellynvdm** [comment]
Amazing news, have a look at https://github.com/getbible/v1#getbible-api-v1 the new easy expansion of the getBible API
