### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by ghost** [getbible/Joomla-3-Component#31]
Hello, I can't use the JSON api in my web-app. Getting this error:
![image](https://user-images.githubusercontent.com/4539476/59750892-37bf4400-9288-11e9-8b78-596832c72fbe.png)

**Comment by Llewellynvdm** [comment]
have you looked over the closed issues here? try [this one](https://github.com/getbible/Joomla-3-Component/issues/23)... or [this one](https://github.com/getbible/Joomla-3-Component/issues/22), or [this one](https://github.com/getbible/Joomla-3-Component/issues/17).. or [this one](https://github.com/getbible/Joomla-3-Component/issues/14) :+1: they all asked the same question. That is why I so delayed to reply. But if those do not resolve your issue let me know.

I am working on a new API for getBible and so I am not fixing the old API unless a major issue arise. The new API will be var better and faster and well.. if the Lord will.

take care!
