### ISSUE TITLE
Links on specific book or chapters

### ISSUE THREAD

**Issue by romagromov** [getbible/Joomla-3-Component#4]
Hi!
Your component builded with jquery.
So, how users can share links on specific book or chapters?
Also, I can't understand how users can add tags?
Thanks.

**Comment by Llewellynvdm** [comment]
We have not yet added share options, but if you go to the app page on your website and you have the membership option enabled in the [back-end of the component] (https://youtu.be/T5dyhbsUKgo) you will see there is an option to email tags and notes to someone. You can also print tags. The tag option only works if you have [membership enabled] (https://youtu.be/T5dyhbsUKgo)  and then it only shows to users who are logged in on your website.
