### ISSUE TITLE
PHP notice in json output

### ISSUE THREAD

**Issue by newjie** [getbible/Joomla-3-Component#6]
live URL:http://nyaii.com/s/index.php?option=com_getbible&view=json&Itemid=225&passage=Jn3:16&v=cus

I installed bible to local and keep getting PHP notice as follows:

Notice: Undefined variable: iVers in /home1/nyaiicom/public_html/s/administrator/components/com_getbible/models/get.php on line 705

Notice: Undefined offset: 1 in /home1/nyaiicom/public_html/s/administrator/components/com_getbible/models/get.php on line 360

Does this have to do with my PHP setting or other joomla components? I use rockettheme's gantry5 framework.

**Comment by Llewellynvdm** [comment]
We have fixed this in our last update, so please install the [latest update] (https://github.com/getbible/Joomla-3-Component/archive/master.zip)
